import unittest
from HTMLTestRunner import HTMLTestRunner

import time

from app56kongpsPro import *

#注册
registerCases = unittest.TestLoader().loadTestsFromTestCase(registerPro.MyTestCase)

#注销
logutCases = unittest.TestLoader().loadTestsFromTestCase(logoutPro.MyTestCase )

#忘记密码
forgotPwdCases = unittest.TestLoader().loadTestsFromTestCase(forgotPwdPro.MyTestCase)

#登录
loginCases = unittest.TestLoader().loadTestsFromTestCase( loginPro.MyTestCase )

#秀足迹
showCases = unittest.TestLoader().loadTestsFromTestCase( showPro.MyTestCase )

#批量提到货（交接按钮）
handoverBatchCases = unittest.TestLoader().loadTestsFromTestCase( handoverBatchPro.MyTestCase )

#单个提货（交接按钮）
handoverPickupCases = unittest.TestLoader().loadTestsFromTestCase( handoverPickupPro.MyTestCase )

#单个到货（交接按钮）
handoverDeliveryProCases = unittest.TestLoader().loadTestsFromTestCase( handoverDeliveryPro.MyTestCase )

#批量提货（首页待提）
PickupBatchCases = unittest.TestLoader().loadTestsFromTestCase( PickupBatchPro.MyTestCase )

#批量到货（首页待到）
DeliveryBatchCases = unittest.TestLoader().loadTestsFromTestCase( DeliveryBatchPro.MyTestCase )

#定检
nodeProCases = unittest.TestLoader().loadTestsFromTestCase( nodePro.MyTestCase )

#我的共享
shareCases = unittest.TestLoader().loadTestsFromTestCase( sharePro.MyTestCase )

#历史任务
historyTaskCases = unittest.TestLoader().loadTestsFromTestCase( historyTaskPro.MyTestCase )

#搜索任务
homeSearchCases = unittest.TestLoader().loadTestsFromTestCase( homeSearchPro.MyTestCase )

#登录失败
loginFaildCases = unittest.TestLoader().loadTestsFromTestCase( loginFaild.MyTestCase )


'''1.全流程'''
'''登录-秀足迹-批量提到货（交接按钮）-单个提货（交接按钮）-单个到货（交接按钮）-
批量提货（首页待提）-批量到货（首页待到）-定检-我的共享-历史任务-搜索任务-注销'''

mysuite = unittest.TestSuite([loginCases,
                              showCases,
                              handoverBatchCases,
                              handoverPickupCases,
                              handoverDeliveryProCases,
                              PickupBatchCases,
                              DeliveryBatchCases,
                              nodeProCases,
                              shareCases,
                              historyTaskCases,
                              homeSearchCases,
                              logutCases])

'''2.提到货流程'''
'''批量提到货（交接按钮）-单个提货（交接按钮）-单个到货（交接按钮）-
批量提货（首页待提）-批量到货（首页待到）'''
mysuite2 = unittest.TestSuite([handoverBatchCases,
                              handoverPickupCases,
                              handoverDeliveryProCases,
                              PickupBatchCases,
                              DeliveryBatchCases])

'''3.登录注册等'''
'''注册-注销-登录'''

mysuite3 = unittest.TestSuite([registerCases,
                               logutCases,
                               loginCases])

'''4.登录失败测试ddt'''
mysuite4 = unittest.TestSuite([loginFaildCases])

now = time.strftime("%Y-%m-%d %H_%M_%S")

with open('report/'+now+'HTML56kongpsReport.html', 'wb') as f:
    myrunner = HTMLTestRunner(stream=f,
                              title='56kongps Test Report',
                              description='generated by HTMLTestRunner.',
                              verbosity=2
                                )
    #unittest.TextTestRunner(verbosity=2)
    myrunner.run(mysuite3)
    f.close()
